
FROM python:3.11

WORKDIR /app
RUN echo "### USING BACKEND RENDER DOCKERFILE ###"


# Copy only requirements first for caching
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

# Expose port
ENV PORT=5000

# Run Gunicorn
CMD ["gunicorn", "app:app", "--workers", "2", "--threads", "4", "--timeout", "300", "--preload", "--bind", "0.0.0.0:$PORT", "--access-logfile", "-", "--error-logfile", "-", "--log-level", "info"]
